//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a0a592_sunamiEntities : DbContext
    {
        public db_a0a592_sunamiEntities()
            : base("name=db_a0a592_sunamiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_extra_item> tbl_extra_item { get; set; }
        public virtual DbSet<tbl_extra_package_customers> tbl_extra_package_customers { get; set; }
        public virtual DbSet<tbl_fault_code> tbl_fault_code { get; set; }
        public virtual DbSet<tbl_faults> tbl_faults { get; set; }
        public virtual DbSet<tbl_imei_sim_numbers> tbl_imei_sim_numbers { get; set; }
        public virtual DbSet<tbl_issues> tbl_issues { get; set; }
        public virtual DbSet<tbl_mpesa_payments> tbl_mpesa_payments { get; set; }
        public virtual DbSet<tbl_mpesa_phone_imei> tbl_mpesa_phone_imei { get; set; }
        public virtual DbSet<tbl_packages> tbl_packages { get; set; }
        public virtual DbSet<tbl_payments> tbl_payments { get; set; }
        public virtual DbSet<tbl_paymode> tbl_paymode { get; set; }
        public virtual DbSet<tbl_system> tbl_system { get; set; }
        public virtual DbSet<tbl_uninstalled_systems> tbl_uninstalled_systems { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<todolistdb> todolistdbs { get; set; }
        public virtual DbSet<tbl_sunami_controller> tbl_sunami_controller { get; set; }
        public virtual DbSet<tbl_switch_logs> tbl_switch_logs { get; set; }
        public virtual DbSet<tbl_expense_categories> tbl_expense_categories { get; set; }
        public virtual DbSet<tbl_expenses> tbl_expenses { get; set; }
        public virtual DbSet<tbl_messages> tbl_messages { get; set; }
        public virtual DbSet<tbl_event_logs> tbl_event_logs { get; set; }
        public virtual DbSet<tbl_inventory> tbl_inventory { get; set; }
        public virtual DbSet<tbl_agents> tbl_agents { get; set; }
    }
}
