//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int Id { get; set; }
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public string phone_numbers { get; set; }
        public string phone_numbers2 { get; set; }
        public string phone_numbers3 { get; set; }
        public string village_name { get; set; }
        public string location { get; set; }
        public string city { get; set; }
        public string Po_Box_Address { get; set; }
        public string next_of_kin { get; set; }
        public string nok_mobile { get; set; }
        public Nullable<bool> active_status { get; set; }
        public string occupation { get; set; }
        public string lon { get; set; }
        public string lat { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public string package_type { get; set; }
        public string RecordedBy { get; set; }
        public string Description { get; set; }
    }
}
