//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grants
    {
        public int id { get; set; }
        public string email { get; set; }
        public string permission_name { get; set; }
        public int office_id { get; set; }
        public int tbl_usersId { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
