//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_event_logs
    {
        public int Id { get; set; }
        public string customer_id { get; set; }
        public string loggedin_user { get; set; }
        public System.DateTime date { get; set; }
        public string @event { get; set; }
        public string category_affected { get; set; }
    }
}
