//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payments
    {
        public int Id { get; set; }
        public string customer_id { get; set; }
        public string imei_number { get; set; }
        public Nullable<int> amount_payed { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> balance { get; set; }
        public string transaction_code { get; set; }
        public Nullable<System.DateTime> date_recorded { get; set; }
        public string person_recording { get; set; }
        public Nullable<int> office_id { get; set; }
    }
}
