//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sunami_controller
    {
        public int Id { get; set; }
        public string imei { get; set; }
        public string sim_no { get; set; }
        public string provider { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> date_manufactured { get; set; }
        public string recorded_by { get; set; }
        public Nullable<int> office_id { get; set; }
    }
}
