//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_packages
    {
        public int Id { get; set; }
        public string type { get; set; }
        public int amount_per_day { get; set; }
        public string description { get; set; }
        public int deposit { get; set; }
        public System.DateTime date_deposit { get; set; }
    }
}
