//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faults
    {
        public int Id { get; set; }
        public string customer_id { get; set; }
        public Nullable<System.DateTime> fault_date { get; set; }
        public string description { get; set; }
        public string error_code { get; set; }
        public Nullable<bool> fixed_status { get; set; }
        public string imei_number { get; set; }
    }
}
