//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agents
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> dateofenrolment { get; set; }
        public string idnumber { get; set; }
        public string country { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public Nullable<int> office_id { get; set; }
    }
}
