//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expenses
    {
        public int Id { get; set; }
        public string description { get; set; }
        public string amount { get; set; }
        public string recipient { get; set; }
        public Nullable<System.DateTime> dateset { get; set; }
        public string account { get; set; }
        public string ref_code { get; set; }
        public byte[] image { get; set; }
        public string RecordedBy { get; set; }
        public string vendor { get; set; }
    }
}
