//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_issues
    {
        public int Id { get; set; }
        public string issue { get; set; }
        public System.DateTime date { get; set; }
        public string reporter { get; set; }
        public string status { get; set; }
        public string customer_id { get; set; }
        public string priority { get; set; }
        public string solvedBy { get; set; }
        public Nullable<System.DateTime> solvedOn { get; set; }
        public string comments { get; set; }
        public Nullable<int> office_id { get; set; }
    }
}
