//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_extra_item
    {
        public int Id { get; set; }
        public string item { get; set; }
        public int amount_per_day { get; set; }
        public int extra_pay_period { get; set; }
        public int deposit { get; set; }
        public Nullable<int> office_id { get; set; }
    }
}
