//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mpesa_payments
    {
        public int Id { get; set; }
        public string number { get; set; }
        public string amount { get; set; }
        public string transaction_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message { get; set; }
        public string phone_imei { get; set; }
        public Nullable<int> office_id { get; set; }
        public string status { get; set; }
    }
}
