//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_system
    {
        public int Id { get; set; }
        public string customer_id { get; set; }
        public Nullable<bool> active_status { get; set; }
        public string current_lon { get; set; }
        public string current_lat { get; set; }
        public Nullable<System.DateTime> last_connected_to_db_date { get; set; }
        public string imei_number { get; set; }
    }
}
