//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunamiapi.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string level { get; set; }
        public bool allow { get; set; }
        public System.DateTime time { get; set; }
        public string token { get; set; }
    }
}
